### ISSUE TITLE
Error during make: Downloading Linux Headers

### ISSUE THREAD

**Issue by MxFxM** [embed-me/ebaz4205_buildroot#1]
Hi,
I am new to buildroot, so this might be my fault, but while running make I encountered this error:

```
>>> linux-headers 4.19 Downloading
--2021-02-20 17:23:45--  https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.tar.xz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving cdn.kernel.org (cdn.kernel.org)... failed: Name or service not known.
wget: unable to resolve host address ‘cdn.kernel.org’
--2021-02-20 17:23:55--  http://sources.buildroot.net/linux/linux-4.19.tar.xz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.0.37, 104.26.1.37, 172.67.72.56, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.0.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-20 17:23:56 ERROR 404: Not Found.

--2021-02-20 17:23:56--  http://sources.buildroot.net/linux-4.19.tar.xz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.0.37, 104.26.1.37, 172.67.72.56, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.0.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-20 17:23:56 ERROR 404: Not Found.

make: *** [package/pkg-generic.mk:148: /home/mxfxm/Buildroots/EBAZ4205/buildroot/output/build/linux-headers-4.19/.stamp_downloaded] Error 1
```

It seems the source urls are responding, but do not find the header version.

I kind of fixed it (I think, is still making) by changing the Linux kernel and header version.

**Comment by embed-me** [comment]
What branch have you fetched from git://git.busybox.net/buildroot?

**Comment by MxFxM** [comment]
Update to the above:
Switching the Linux kernel to 5.10 and the Linux headers as well, I was able to finish the build.

I got buildroot using this command:
`$ git clone https://github.com/buildroot/buildroot.git buildroot`
which does not satisfy your dependency with:
```
URI: git://git.busybox.net/buildroot
branch: 2020.11.x
```
but I checked the mirrors and download locations in the build options and they match.

**Comment by embed-me** [comment]
Please try to build the project with the correct branch and let me know if the problem persists.

**Comment by MxFxM** [comment]
Yup, it was my fault for using a different version...

However I had to apply this patch:
https://github.com/Tomoms/android_kernel_oppo_msm8974/commit/11647f99b4de6bc460e106e876f72fc7af3e54a6

To uboot and linux4.19

**Comment by embed-me** [comment]
Thanks for letting me know. Don't think the patch is required either, however, I will close the issue for now.
